Repository hashicorp/vscode-terraform, pull requests merged in 2021-08, with the labels that each got.

#718 github: further improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#721 build: Introduce dependabot for updating deps
  .github/dependabot.yml
Labels: dependencies, build

#728 github: Reduce timeouts
  .github/workflows/test.yml
Labels: build

#741 src/clientHandler: add support for certain CLI options
  package.json
  src/clientHandler.ts
Labels: enhancement
