Repository hashicorp/vscode-terraform, pull requests merged in 2021-07, with the labels that each got.

#688 Fix DocumentSelector for multi-folder workspace
  .github/workflows/test.yml
  package.json
  src/clientHandler.ts
  src/extension.ts
  src/test/workspaces.test.ts
Labels: bug

#690 fix language server update logic
  src/clientHandler.ts
  src/extension.ts
Labels: bug

#693 Readme: Mention tip about default formatter
  README.md
Labels: documentation

#694 fix: launch LS even if path contains escapable characters
  src/languageServerInstaller.ts
  src/test/runTest.ts
  src/utils.ts
Labels: bug

#691 Improve error handling
  package-lock.json
  package.json
  src/clientHandler.ts
  src/extension.ts
  src/serverPath.ts
Labels: enhancement

#686 Register command to show references
  src/clientHandler.ts
  src/showReferences.ts
Labels: enhancement

#656 (GH-628) Add semver based version pin for Language Server
  package.json
  src/extension.ts
  src/languageServerInstaller.ts
Labels: enhancement
