Repository hashicorp/vscode-terraform, pull requests merged in 2021-09, with the labels that each got.

#777 ci: constraint Terraform for testing to `~1.0`
  .github/workflows/test.yml
Labels: build

#775 package.json: prevent accidental npm publishing
  package.json
Labels: build

#778 fix: avoid tracking client which is not ready yet
  src/clientHandler.ts
  src/extension.ts
Labels: bug

#771 fix: avoid considering output panes as editors
  src/clientHandler.ts
  src/extension.ts
  src/vscodeUtils.ts
Labels: bug

#776 ci: Read node version from nvmrc
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: build

#784 ci: change windows-style slash to unix-style
  .github/workflows/build.yml
Labels: build

#746 Module View Provider
  assets/icons/terraform.svg
  package.json
  src/extension.ts
  src/providers/moduleProvider.ts
Labels: enhancement

#795 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#794 Update launch configuration and tasks
  .vscode/launch.json
  .vscode/tasks.json
  package.json
Labels: build

#792 Prevent Module View Provider from failing to call LS
  package.json
  src/providers/moduleProvider.ts
Labels: bug
