Repository hashicorp/vscode-terraform, pull requests merged in 2021-11, with the labels that each got.

#841 Fix ModuleProvider starting before client ready
  src/extension.ts
Labels: bug

#848 Fix Warnings
  src/extension.ts
  src/providers/moduleProvider.ts
  src/test/integration/workspaces.test.ts
  src/utils.ts
Labels: bug

#814 Publish preview builds
  .github/workflows/preview.yml
  build/nightly.md
  build/preview
  package.json
Labels: build

#845 Refactor to Single Language Client
  CHANGELOG.md
  src/clientHandler.ts
  src/extension.ts
  src/providers/moduleProvider.ts
  src/serverPath.ts
  src/vscodeUtils.ts
Labels: enhancement

#851 Generate bug report command
  package.json
  src/commands/generateBugReport.ts
  src/extension.ts
Labels: enhancement

#852 Use vscode.workspace.fs instead of fs package
  package.json
  src/clientHandler.ts
  src/languageServerInstaller.ts
  src/serverPath.ts
Labels: enhancement

#854 Fix extension ignore list for packaging
  .vscodeignore
Labels: build

#823 Process telemetry from language server
  src/clientHandler.ts
  src/telemetry.ts
Labels: enhancement
