Repository hashicorp/vscode-terraform, pull requests merged in 2022-04, with the labels that each got.

#1024 Organize extension settings into Sections
  package.json
Labels: enhancement

#1038 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: ci

#1032 Prevent preview from activating when stable is enabled
  src/extension.ts
Labels: enhancement

#1031 Add terraform.languageServer.ignoreSingleFileWarning setting
  package.json
  src/clientHandler.ts
Labels: enhancement

#1039 Add missing descriptions to semantic token types & modifiers
  package.json
Labels: bug

#1034 Fix LANGUAGE_SERVER_VERSION test in preview script
  build/preview
Labels: bug

#1049 Deprecate terraform-ls.rootmodule and terraform-ls.excludeRootModules
  package.json
Labels: documentation

#1060 deps: bump LS to 0.27.0
  build/downloader.ts
  package.json
Labels: enhancement

#1062 Remove `terraform.languageServer.maxNumberOfProblems`
  package.json
Labels: breaking

#1065 Add Module Providers view refresh button
  package.json
  src/providers/moduleProviders.ts
Labels: enhancement

#1072 dependabot: Reduce interval for dev dependencies to weekly
  .github/dependabot.yml
Labels: ci

#1073 Organize Static Features
  src/clientHandler.ts
  src/extension.ts
  src/features/semanticTokens.ts
  src/features/showReferences.ts
  src/features/telemetry.ts
  src/features/types.ts
  src/semanticTokens.ts
Labels: technical-debt

#1074 Move utility functions to dedicated space
  src/clientHandler.ts
  src/extension.ts
  src/installer/detector.ts
  src/providers/moduleCalls.ts
  src/providers/moduleProviders.ts
  src/test/runTest.ts
  src/test/unit/detector.test.ts
  src/utils.ts
  src/utils/helpers.ts
  src/utils/serverPath.ts
  src/utils/vscode.ts
Labels: technical-debt

#1075 Remove command prefix
  package-lock.json
  package.json
  src/clientHandler.ts
  src/extension.ts
  src/providers/moduleCalls.ts
  src/providers/moduleProviders.ts
Labels: technical-debt

#1079 Optimize main entry point execution path
  src/extension.ts
Labels: technical-debt

#1082 Extract LanguageClient from ClientHandler
  src/clientHandler.ts
  src/extension.ts
  src/providers/moduleCalls.ts
  src/providers/moduleProviders.ts
  src/utils/clientHelpers.ts
  src/utils/serverPath.ts
Labels: technical-debt
