Repository hashicorp/vscode-terraform, pull requests merged in 2022-02, with the labels that each got.

#912 Terraform TextMate Test Infrastructure
  .github/workflows/test.yml
  .vscode/extensions.json
  .vscode/settings.json
  DEVELOPMENT.md
  jest.config.js
  package-lock.json
  package.json
  tests/snapshot/terraform/basic.tf
  tests/snapshot/terraform/basic.tf.snap
  tests/unit/terraform/basic.tf
Labels: enhancement, build, documentation

#916 Update vsce to 2.6.6
  package-lock.json
  package.json
Labels: dependencies, build

#918 Update list/map syntax highlighting
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/variables_input.tf.snap
Labels: bug

#921 Move TextMate scope.terraform to source.terraform
  package.json
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/basic.tf.snap
  tests/snapshot/terraform/blocks.tf.snap
  tests/snapshot/terraform/comments.tf.snap
  tests/snapshot/terraform/data_sources.tf.snap
  tests/snapshot/terraform/expressions_conditional.tf.snap
  tests/snapshot/terraform/expressions_dynamic.tf.snap
  tests/snapshot/terraform/expressions_for.tf.snap
  tests/snapshot/terraform/expressions_functions.tf.snap
  tests/snapshot/terraform/expressions_operators.tf.snap
  tests/snapshot/terraform/expressions_splat.tf.snap
  tests/snapshot/terraform/expressions_strings.tf.snap
  tests/snapshot/terraform/modules.tf.snap
  tests/snapshot/terraform/providers.tf.snap
  tests/snapshot/terraform/variables_input.tf.snap
  tests/snapshot/terraform/variables_local.tf.snap
  tests/snapshot/terraform/variables_output.tf.snap
  tests/unit/terraform/basic.tf
Labels: syntax

#922 Run syntax tests when grammar changes
  .github/workflows/syntax.yml
  .github/workflows/test.yml
Labels: syntax, build

#925 Fix Nested Map Highlighting
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/basic.tf.snap
  tests/snapshot/terraform/data_sources.tf.snap
  tests/snapshot/terraform/expressions_for.tf.snap
  tests/snapshot/terraform/expressions_operators.tf.snap
  tests/snapshot/terraform/nested_maps.tf
  tests/snapshot/terraform/nested_maps.tf.snap
  tests/snapshot/terraform/variables_input.tf.snap
  tests/snapshot/terraform/variables_local.tf.snap
  tests/unit/terraform/basic.tf
Labels: bug, syntax

#928 Fix npm run syntax tests
  package.json
Labels: build

#930 Test CI Ignore changes to markdown files
  .github/workflows/test.yml
Labels: build

#931 Allow manual preview publishing only
  .github/workflows/preview.yml
Labels: build

#937 Resolve issue with tfvars comment toggling
  package.json
Labels: enhancement, syntax

#924 Restore region markers support
  language-configuration.json
Labels: enhancement, syntax

#939 Update to @vscode/extension-telemetry
  package-lock.json
  package.json
  src/clientHandler.ts
  src/extension.ts
  src/telemetry.ts
Labels: dependencies

#934 Add new scope for block type and name
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/basic.tf.snap
  tests/snapshot/terraform/blocks.tf.snap
  tests/snapshot/terraform/data_sources.tf.snap
  tests/snapshot/terraform/expressions_dynamic.tf.snap
  tests/snapshot/terraform/issue927.tf.snap
  tests/snapshot/terraform/modules.tf.snap
  tests/snapshot/terraform/providers.tf.snap
  tests/snapshot/terraform/variables_input.tf.snap
  tests/snapshot/terraform/variables_local.tf.snap
  tests/snapshot/terraform/variables_output.tf.snap
  tests/unit/terraform/basic.tf
  tests/unit/terraform/resource.tf
Labels: syntax

#940 Fix highlighting for nested expression syntax
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/expressions_for.tf
  tests/snapshot/terraform/expressions_for.tf.snap
Labels: bug, syntax

#946 Fix ignore markdown files
  .github/workflows/test.yml
Labels: bug, build

#945 Update description for log file argument
  package.json
Labels: bug

#942 Improve Extension Documentation
  .vscodeignore
  DEVELOPMENT.md
  README.md
  docs/code_lens.png
  docs/intellisense1.png
  docs/intellisense2.png
  docs/intellisense3.png
  docs/module_calls.png
  docs/module_calls_doc_link.png
  docs/module_providers.png
  docs/pin_version.png
  docs/pre-fill.png
  docs/syntax.png
Labels: documentation
