Repository hashicorp/vscode-terraform, pull requests merged in 2022-05, with the labels that each got.

#1084 Automatically refresh Terraform Providers View when providers change in open document
  CHANGELOG.md
  src/extension.ts
  src/features/moduleProviders.ts
  src/features/types.ts
  src/providers/moduleProviders.ts
Labels: enhancement

#1089 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1096 Readme: Fix broken image URL
  README.md
Labels: documentation

#1094 Remove vscode-tmgrammar-test
  package-lock.json
  package.json
Labels: dependencies, technical-debt

#1097 Update README
  README.md
  build/preview
Labels: documentation

#1113 github: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#1114 Bump syntax 0.3.0
  CHANGELOG.md
  package.json
Labels: bug, syntax
