Repository hashicorp/vscode-terraform, pull requests merged in 2022-08, with the labels that each got.

#1200 Refactor main entry point
  src/commands/terraform.ts
  src/commands/terraformls.ts
  src/extension.ts
  src/features/moduleCalls.ts
  src/features/moduleProviders.ts
  src/features/showReferences.ts
  src/features/telemetry.ts
  src/handlers/errorHandler.ts
  src/settings.ts
  src/utils/clientHelpers.ts
Labels: technical-debt

#1203 fix: avoid sending command ID when codelens is disabled
  src/features/showReferences.ts
Labels: bug

#1201 Update CHANGELOG for 0.24.0
  CHANGELOG.md
Labels: enhancement

#1204 Bump terraform-ls from 0.28.1 to 0.29.0
  package.json
Labels: dependencies

#1209 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1215 Improve error telemetry
  src/extension.ts
  src/handlers/errorHandler.ts
Labels: technical-debt
