Repository hashicorp/vscode-terraform, pull requests merged in 2022-03, with the labels that each got.

#952 Release 2.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#962 Use dependabot to update GitHub Actions
  .github/dependabot.yml
Labels: build

#968 github: pin Windows to 2019 to prevent timeouts
  .github/workflows/test.yml
Labels: build

#989 Advertise proper exectution location
  package.json
Labels: bug

#1000 Release 2.20.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: build

#1002 bump LS to 0.26.0
  package.json
  src/test/integration/workspaces.test.ts
Labels: dependencies

#1005 deps: bump syntax to v0.2.0
  package.json
Labels: dependencies

#1010 Deprecate maxNumberOfProblems
  package.json
Labels: enhancement, breaking

#1019 Format semantic token settings
  .github/workflows/test.yml
  .prettierignore
Labels: build
