Repository hashicorp/vscode-terraform, pull requests merged in 2023-09, with the labels that each got.

#1565 Add sleep to code action test
  src/test/integration/codeAction.test.ts
Labels: technical-debt

#1564 Bump Terraform version in CI
  .github/workflows/test.yml
  src/test/integration/completion.test.ts
Labels: ci

#1563 deps: Bump js-releases to 1.7.0
  package-lock.json
Labels: dependencies
