Repository hashicorp/vscode-terraform, pull requests merged in 2024-01, with the labels that each got.

#1659 Fix test failures on main
  .github/workflows/test.yml
  .vscode/settings.json
  src/test/integration/codeAction.test.ts
Labels: bug

#1660 Bump minimal engine version to `1.82.3`
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
Labels: breaking

#1663 github: Revert upgrade of artifact actions
  .github/workflows/deploy.yml
Labels: dependencies

#1643 Configure command enablement
  package.json
  src/features/terraformCloud.ts
Labels: terraform-cloud

#1664 Rename `hcl-traversalStep` to `hcl-referenceStep`
  package.json
Labels: technical-debt

#1680 Add CONTRIBUTING file
  .github/CONTRIBUTING.md
Labels: documentation
