Repository hashicorp/vscode-terraform, pull requests merged in 2024-05, with the labels that each got.

#1751 Replace outdated remove-labels action with `gh`
  .github/workflows/issue-comment-created.yml
Labels: ci

#1752 Reenable Dependabot for internal GitHub actions
  .github/dependabot.yml
Labels: dependencies

#1759 Remove old testing infra
  .changes/unreleased/INTERNAL-20240523-135953.yaml
  .github/workflows/test.yml
  .vscode/launch.json
  package.json
  src/web/test/integration/extension.test.ts
  src/web/test/integration/index.ts
  webpack.config.js
Labels: technical-debt

#1762 Cache npm packages in GitHub Actions
  .changes/unreleased/INTERNAL-20240524-100633.yaml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: technical-debt

#1761 Use esbuild with webpack
  .changes/unreleased/INTERNAL-20240523-141243.yaml
  package-lock.json
  package.json
  webpack.config.js
Labels: technical-debt

#1758 Organize code placement
  .changes/unreleased/INTERNAL-20240523-140044.yaml
  src/api/terraform/terraform.ts
  src/api/terraformCloud/account.ts
  src/api/terraformCloud/apply.ts
  src/api/terraformCloud/configurationVersion.ts
  src/api/terraformCloud/errors.ts
  src/api/terraformCloud/filter.ts
  src/api/terraformCloud/index.ts
  src/api/terraformCloud/ingressAttribute.ts
  src/api/terraformCloud/log.ts
  src/api/terraformCloud/organization.ts
  src/api/terraformCloud/pagination.ts
  src/api/terraformCloud/plan.ts
  src/api/terraformCloud/project.ts
  src/api/terraformCloud/run.ts
  src/api/terraformCloud/user.ts
  src/api/terraformCloud/workspace.ts
  src/commands/terraform.ts
  src/extension.ts
  src/features/moduleCalls.ts
  src/features/moduleProviders.ts
  src/features/terraformCloud.ts
  src/features/terraformVersion.ts
  src/providers/terraform/moduleCalls.ts
  src/providers/terraform/moduleProviders.ts
  src/providers/tfc/applyProvider.ts
  src/providers/tfc/authenticationProvider.ts
  src/providers/tfc/contentProvider.ts
  src/providers/tfc/helpers.ts
  src/providers/tfc/logHelpers.ts
  src/providers/tfc/organizationPicker.ts
  src/providers/tfc/planProvider.ts
  src/providers/tfc/runProvider.ts
  src/providers/tfc/uiHelpers.ts
  src/providers/tfc/workspaceFilters.ts
  src/providers/tfc/workspaceProvider.ts
  src/test/integration/mocks/server.ts
  src/test/mockSetup.ts
Labels: technical-debt
